global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'mercadolivre-monitor'

# Alertmanager configuration (opcional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: []

# Load rules once and periodically evaluate them (opcional)
# rule_files:
#   - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  # Métricas da aplicação Spring Boot
  - job_name: 'vendasml'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'vendasml'
          environment: 'development'

  # Métricas do Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

